from pathlib import Path

path = Path("app/studio/page.tsx")
text = path.read_text()
text_n = text.replace("\r\n", "\n")
old_block = """  useEffect(() => {\n    const loadHistory = async () => {\n      try {\n        const res = await fetch(\"/api/images/history\", { cache: \"no-store\" })\n        if (!res.ok) {\n          throw new Error(`HTTP ${res.status}`)\n        }\n        const json = (await res.json()) as { images?: GeneratedImage[] }\n        if (Array.isArray(json.images) && json.images.length > 0) {\n          const sorted = [...json.images].sort(\n            (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),\n          )\n          setHistory(sorted)\n          setGeneratedImage((prev) => prev ?? sorted[0]?.imagePath)\n          setLastDescription((prev) => prev ?? sorted[0]?.description ?? null)\n          setSelectedImageIndex(0)\n        }\n      } catch (error) {\n        console.error(\"[studio] Failed to load history\", error)\n      }\n    }\n\n    void loadHistory()\n  }, [])\n\n"""
new_block = """  const loadHistory = useCallback(async () => {\n    try {\n      setHistoryLoading(true)\n      setHistoryError(null)\n\n      const res = await fetch(\"/api/images/history\", { cache: \"no-store\" })\n      if (!res.ok) {\n        throw new Error(`HTTP ${res.status}`)\n      }\n\n      const json = (await res.json()) as { images?: GeneratedImage[] }\n      const images = Array.isArray(json.images) ? json.images : []\n      const sorted = [...images].sort(\n        (a, b) => new Date(b.createdAt ?? 0).getTime() - new Date(a.createdAt ?? 0).getTime(),\n      )\n      setHistory(sorted)\n      if (sorted.length > 0) {\n        setGeneratedImage((prev) => prev ?? sorted[0]?.imagePath)\n        setLastDescription((prev) => prev ?? sorted[0]?.description ?? null)\n        setSelectedImageIndex(0)\n      } else {\n        setGeneratedImage(undefined)\n        setLastDescription(null)\n        setSelectedImageIndex(0)\n      }\n    } catch (error) {\n      console.error(\"[studio] Failed to load history\", error)\n      setHistoryError(error instanceof Error ? error.message : \"Failed to load images\")\n    } finally {\n      setHistoryLoading(false)\n    }\n  }, [])\n\n  useEffect(() => {\n    void loadHistory()\n  }, [loadHistory])\n\n"""
if old_block not in text_n:
    raise SystemExit("Could not locate loadHistory block")
text_n = text_n.replace(old_block, new_block, 1)
path.write_text(text_n.replace("\n", "\r\n"))
